name: Deploy Next.js App

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Create Deployment Package
        run: |
          mkdir -p /tmp/deploy
          rsync -av --exclude=node_modules --exclude=.git ./ /tmp/deploy/
          tar -czf deploy.tar.gz -C /tmp/deploy .

      - name: Transfer Files to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          source: "deploy.tar.gz"
          target: "https://cloud-asrs.vercel.app/"

      - name: SSH into Server and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          script: |
            cd https://cloud-asrs.vercel.app/
            rm -rf *  # Remove old files (optional, be careful with this)
            tar -xzf ../deploy.tar.gz -C .  # Extract new files
            npm install  # Install dependencies
            npm run build  # Build Next.js app
            pm2 restart next-app || pm2 start npm --name "next-app" -- start -- -p 2024
            pm2 save
            rm ../deploy.tar.gz  # Clean up the archive file
